import { PostgresConnectionOptions } from 'typeorm/driver/postgres/PostgresConnectionOptions';
import Users from '../authentication/users.entity';
import Tasks from '../tasks/tasks.entity';

const pgSchema = process.env.DB_SCHEMA || 'public';

export enum AUTH_GUARD_TYPES_ENUM {
  ADMIN,
  AUTHORIZED,
}

export enum MUSIC_NOTES_ENUM {
  C2 = 'C2',
  D2 = 'D2',
  E2 = 'E2',
  F2 = 'F2',
  G2 = 'G2',
  A2 = 'A2',
  B2 = 'B2',
  C3 = 'C3',
  D3 = 'D3',
  E3 = 'E3',
  F3 = 'F3',
  G3 = 'G3',
  A3 = 'A3',
  B3 = 'B3',
  C4 = 'C4',
  D4 = 'D4',
  E4 = 'E4',
  F4 = 'F4',
  G4 = 'G4',
  A4 = 'A4',
  B4 = 'B4',
  C5 = 'C5',
  D5 = 'D5',
  E5 = 'E5',
  F5 = 'F5',
  G5 = 'G5',
  A5 = 'A5',
  B5 = 'B5',
  C6 = 'C6',
  D6 = 'D6',
  E6 = 'E6',
  F6 = 'F6',
  G6 = 'G6',
  A6 = 'A6',
  B6 = 'B6',
  C7 = 'C7',
  Csharp2 = 'C#2',
  Dsharp2 = 'D#2',
  Fsharp2 = 'F#2',
  Gsharp2 = 'G#2',
  Asharp2 = 'A#2',
  Csharp3 = 'C#3',
  Dsharp3 = 'D#3',
  Fsharp3 = 'F#3',
  Gsharp3 = 'G#3',
  Asharp3 = 'A#3',
  Csharp4 = 'C#4',
  Dsharp4 = 'D#4',
  Fsharp4 = 'F#4',
  Gsharp4 = 'G#4',
  Asharp4 = 'A#4',
  Csharp5 = 'C#5',
  Dsharp5 = 'D#5',
  Fsharp5 = 'F#5',
  Gsharp5 = 'G#5',
  Asharp5 = 'A#5',
  Csharp6 = 'C#6',
  Dsharp6 = 'D#6',
  Fsharp6 = 'F#6',
  Gsharp6 = 'G#6',
  Asharp6 = 'A#6',
}

export const port = +process.env.PORT || 3000;
export const database: PostgresConnectionOptions = {
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: +process.env.DB_PORT || 5432,
  username: process.env.DB_USERNAME || 'postgres',
  password: process.env.DB_PASSWORD || 'postgres',
  database: process.env.DB_NAME || 'postgres',
  schema: pgSchema,
  entities: [Users, Tasks],
  synchronize: true,
};
export const jwt = {
  secret: process.env.JWT_SECRET || 'strongSecretKey',
  expiresIn: process.env.JWT_EXPIRES_IN || '60h',
};
